objects/eSignGenieConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token_Generated_Date__c</fullName>
        <label>Access Token Generated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expires_In__c</fullName>
        <label>Expires In</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eSign Genie Configuration</label>
</CustomObject>

classes/eSignGenieConfigController.cls
public with sharing class eSignGenieConfigController {
    public eSignGenieConfiguration__c eSignGenieConfigObj{get;set;}
    public boolean showConnectBtn {get;set;}
    
    public eSignGenieConfigController(){
        eSignGenieConfigObj = eSignGenieConfiguration__c.getInstance('Configuration');
        if(eSignGenieConfigObj.Access_Token__c != null){
            showConnectBtn  = false;
        }else{
            showConnectBtn = true;
        }
    }
    
    public PageReference removeAccessToken(){
        if(eSignGenieConfigObj.Access_Token__c != null){
            system.debug('Id is ++++++' + eSignGenieConfigObj.id);
            system.debug('Name is ++++' + eSignGenieConfigObj.name);
            eSignGenieConfiguration__c eSignConf = new eSignGenieConfiguration__c(Id=eSignGenieConfigObj.id,name=eSignGenieConfigObj.name,Access_Token__c=null,Refresh_Token__c=null,Access_Token_Generated_Date__c = null,Expires_In__c=null);
            update eSignConf;
            showConnectBtn = true;            
        }
        return null;
    }
}