objects/eSignGenieConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eSign_Genie_Api_URL__c</fullName>
        <label>eSign Genie Api URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eSign Genie Configuration</label>
</CustomObject>

objects/Folder_Details_With_Obj_Name__c.object
<CustomObject>
    <fields>
        <fullName>Folder_Id__c</fullName>
        <label>Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Status__c</fullName>
        <label>Folder Status</label>
        <picklist>
            <picklistValues>
                <fullName>SHARED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY SIGNED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRAFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPIRED</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>eSignGenie Folder Detail</label>
    <nameField>
        <label>Folder Details With Obj Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eSignGenie Folder Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DisplayDocumentPageControllerTest.cls
@isTest
public class DisplayDocumentPageControllerTest {
    public static testmethod void method1(){
        List<Folder_Details_With_Obj_Name__c> lstDtls = [select id,Folder_Id__c from Folder_Details_With_Obj_Name__c];
        ApexPages.currentPage().getParameters().put('sfRcrdId',lstDtls.get(0).Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        test.startTest();
        DisplayDocumentPageController dsObj = new DisplayDocumentPageController();
        system.assertEquals(lstDtls.get(0).Folder_Id__c,'1');
        test.stopTest();
    }
    
    @testSetup
    Static void insertData(){
        eSignGenieConfiguration__c confObj = new eSignGenieConfiguration__c();
        confObj.Name = 'Configuration';
        confObj.Client_ID__c = 'test';
        confObj.Client_Secret__c = 'test';
        confObj.Access_Token__c = 'test';
        confObj.eSign_Genie_Api_URL__c = 'https://www.esigngenie.com/esign/api';
        insert confObj;
        
        List<Folder_Details_With_Obj_Name__c> lstFldrDtls = new List<Folder_Details_With_Obj_Name__c>();
        Folder_Details_With_Obj_Name__c f1 = new Folder_Details_With_Obj_Name__c();
        f1.Folder_Id__c = '1';
        f1.Folder_Status__c = 'DRAFT';
        lstFldrDtls.add(f1);
        insert lstFldrDtls;
        
        system.assertEquals(f1.Folder_Id__c, '1');
    }
}