objects/ESignGenie_Log__c.object
<CustomObject>
    <fields>
        <fullName>API_Url__c</fullName>
        <label>API Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <picklist>
            <picklistValues>
                <fullName>Debug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ESignGenie Log</label>
    <nameField>
        <label>ESignGenie Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ESignGenie Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eSignGenieConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eSign_Genie_Api_URL__c</fullName>
        <label>eSign Genie Api URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eSign Genie Configuration</label>
</CustomObject>

classes/eSignGenieUtils.cls
public with sharing class eSignGenieUtils {
    public static String sendESignGenieReqst(String url,String methodType, String payload){
        eSignGenieConfiguration__c eSignGenieConfigObj = eSignGenieConfiguration__c.getInstance('Configuration');
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        String responseBody;
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Authorization', 'Bearer ' + eSignGenieConfigObj.Access_Token__c);
        req.setMethod(methodType);
        system.debug('URL is ::::::'+eSignGenieConfigObj.eSign_Genie_Api_URL__c + url);
        req.setEndpoint(eSignGenieConfigObj.eSign_Genie_Api_URL__c+url);
        if(payload != null && payload != ''){
            req.setBody(payload);
            system.debug('Request Payload Is ::::::'+ payload);
        }
        try{
            req.setTimeout(120000);
            res = http.send(req);
            responseBody = res.getBody();
            system.debug('RESPONSE IS :::::::' + responseBody);
        } 
        catch (Exception e) {
            ESignGenie_Log__c logObj = new ESignGenie_Log__c();
            logobj.API_Url__c = eSignGenieConfigObj.eSign_Genie_Api_URL__c+url;
            logobj.Response__c = res.getBody();
            logobj.Payload__c = payload;
            logObj.Log_Type__c = 'Error';
            logobj.Exception_Message__c = 'Exception is :' + e;
            if (Schema.sObjectType.ESignGenie_Log__c.isCreateable()) {
                insert logObj;
            }
        }
        
        return responseBody;
    }
}