objects/Folder_Details_With_Obj_Name__c.object
<CustomObject>
    <fields>
        <fullName>Folder_Creation_Date__c</fullName>
        <label>Folder Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Folder_Document_Ids__c</fullName>
        <label>Folder Document Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Id__c</fullName>
        <label>Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Sent_Date__c</fullName>
        <label>Folder Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Folder_Status__c</fullName>
        <label>Folder Status</label>
        <picklist>
            <picklistValues>
                <fullName>SHARED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY SIGNED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRAFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPIRED</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Record_Id__c</fullName>
        <label>SF Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eSignGenie Folder Detail</label>
    <nameField>
        <label>Folder Details With Obj Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eSignGenie Folder Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateFolderStatusService.cls
@RestResource(urlMapping='/UpdateFolderStatus/*')
global with sharing class UpdateFolderStatusService{
    @HttpPost 
    global static void  doPost(){
        RestRequest restreq = RestContext.request;
        RestResponse res = RestContext.response;
        
        String postBody = restreq.requestBody.toString();
        RequestWrapper rqstWrprObj = (RequestWrapper) JSON.deserialize(postBody, RequestWrapper.class);
        
        
        String folderId = rqstWrprObj.folderId;
        String updatedFldrStatus = rqstWrprObj.updatedStatus;
        
        ResponseWrapper resp = new ResponseWrapper();
        
        List<Folder_Details_With_Obj_Name__c> lstFldrDtls = [SELECT Folder_Id__c,Folder_Name__c,Folder_Status__c,Folder_Creation_Date__c,Folder_Sent_Date__c,Folder_Document_Ids__c,Object_Name__c,SF_Record_Id__c FROM Folder_Details_With_Obj_Name__c where Folder_Id__c =: folderId];
        if(lstFldrDtls != null && lstFldrDtls.size() > 0){
            if(lstFldrDtls.get(0).Folder_Status__c != updatedFldrStatus){
                lstFldrDtls.get(0).Folder_Status__c = updatedFldrStatus;
                update lstFldrDtls;
                resp.status = 'Success';
            }else{
                resp.status = 'Failure';
            }            
            String query = 'select id,folderId__c,folderStatus__c from ' + lstFldrDtls.get(0).Object_Name__c + ' where id = \'' + lstFldrDtls.get(0).SF_Record_Id__c + '\'';
            List<SObject> lstObjs = Database.query(query);
            if(lstObjs != null && lstObjs.size() > 0){
                if(lstObjs.get(0).get('folderStatus__c') != updatedFldrStatus){
                    lstObjs.get(0).put('folderStatus__c',updatedFldrStatus); 
                    update lstObjs;                    
                    // resp.status = 'Success';
                }else{
                    // resp.status = 'Failure';
                }               
            }
            String resp_JSON = JSON.serializePretty(resp);
            res.responseBody = Blob.valueOf(resp_JSON);
        }else{
            resp.status = 'Failure';
            String resp_JSON = JSON.serializePretty(resp);
            res.responseBody = Blob.valueOf(resp_JSON);
        }
    }
    
    global class RequestWrapper{
        public String folderId;
        public String updatedStatus;
    }
    
    global class ResponseWrapper{
        public String status;
    }
}