objects/Folder_Details_With_Obj_Name__c.object
<CustomObject>
    <fields>
        <fullName>Folder_Creation_Date__c</fullName>
        <label>Folder Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Folder_Document_Ids__c</fullName>
        <label>Folder Document Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Id__c</fullName>
        <label>Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Sent_Date__c</fullName>
        <label>Folder Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Folder_Status__c</fullName>
        <label>Folder Status</label>
        <picklist>
            <picklistValues>
                <fullName>SHARED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY SIGNED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRAFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPIRED</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Record_Id__c</fullName>
        <label>SF Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eSignGenie Folder Detail</label>
    <nameField>
        <label>Folder Details With Obj Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eSignGenie Folder Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchFolderStatusUpdate.cls
global with sharing class BatchFolderStatusUpdate implements Database.Batchable<SObject>,Database.AllowsCallouts, Database.Stateful  {
    
    global final String query;
    global String objName;
    
    /*global BatchFolderStatusUpdate(String objName){
        this.objName = objName;
        this.query = 'select id, folderId__c,folderName__c,folderStatus__c,folderDocumentIds__c from ' + objName+ ' where folderStatus__c != \'CANCELLED\' and folderStatus__c != \'SIGNED\' ';
    }*/
    
    global BatchFolderStatusUpdate(){
        this.query = 'SELECT Folder_Id__c,Folder_Name__c,Folder_Status__c,Folder_Creation_Date__c,Folder_Sent_Date__c,Folder_Document_Ids__c,Object_Name__c,SF_Record_Id__c FROM Folder_Details_With_Obj_Name__c where Folder_Status__c != null and Folder_Status__c not in (\'CANCELLED\',\'EXECUTED\') ';
    }
    
    global Database.QueryLocator  start(Database.BatchableContext BC)  {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope)  {
        List<SObject> lstSObjs = new List<SObject>();
        for(SObject s : scope){
            if(s.get('Folder_Id__c') != null){
                String resBody = eSignGenieUtils.sendESignGenieReqst('/folders/myfolder?folderId='+s.get('Folder_Id__c'), 'GET', null);
                ResponseWrapper rspnWrprObj = (ResponseWrapper)JSON.deserialize(resBody,ResponseWrapper.class);
                FolderDetails fldrDtlObj = rspnWrprObj.folder;
                if(s.get('Folder_Status__c') == null || s.get('Folder_Status__c') != fldrDtlObj.folderStatus){
                    s.put('Folder_Status__c',fldrDtlObj.folderStatus);
                    lstSObjs.add(s);
                }
            }            
        }        
        update lstSObjs;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
    public class ResponseWrapper{
        public FolderDetails folder;
    }
    
    public class FolderDetails{
        public String folderId;
        public String folderName;
        public String folderStatus;
    }
}