objects/Mapping_Child_Obj__c.object
<CustomObject>
    <fields>
        <fullName>Mapping_Parent_Obj__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mapping Parent Obj</label>
        <referenceTo>Mapping_Parent_Obj__c</referenceTo>
        <relationshipLabel>Mapping Child Objs</relationshipLabel>
        <relationshipName>Mapping_Child_Objs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mapping Child Obj</label>
    <nameField>
        <label>Mapping Child Obj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Child Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mapping_Parent_Obj__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Default_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default Mapping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Name__c</fullName>
        <label>Mapping Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Obj_Name__c</fullName>
        <label>Parent Obj Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_File_Name__c</fullName>
        <label>Template File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <label>Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Parent Obj</label>
    <nameField>
        <label>Mapping Parent Obj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Parent Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllMappingNameController.cls
public with sharing class AllMappingNameController {
    public Id mapId{get;set;}
    public String rowNo {get;set;}
    public Map<String,String> mapObjLabelToName {get;set;}
    public List<Mapping_Parent_Obj__c> lstMapParent {get;set;}
    public List<Mapping_Parent_Obj__c> lstActiveMapping {get;set;}
    public List<Mapping_Parent_Obj__c> lstDeActiveMapping {get;set;}
    
    public AllMappingNameController(){
        mapObjLabelToName = new map<String,String>();
        lstMapParent = new List<Mapping_Parent_Obj__c>();
        lstActiveMapping = new List<Mapping_Parent_Obj__c>();
        lstDeActiveMapping = new List<Mapping_Parent_Obj__c>();
        
        for ( Schema.SObjectType o : Schema.getGlobalDescribe().values() ){
            Schema.DescribeSObjectResult objResult = o.getDescribe();
            mapObjLabelToName.put(objResult.getName(),objResult.getLabel());   
        }
        
        lstMapParent = [select Id,Mapping_Name__c,Parent_Obj_Name__c,Template_Name__c,Is_Active__c,Is_Default_Mapping__c,Template_File_Name__c from Mapping_Parent_Obj__c limit 10000];
        
        for(Mapping_Parent_Obj__c m : lstMapParent){
            if(m.Is_Active__c == true){
                lstActiveMapping.add(m);
            }else{
                lstDeActiveMapping.add(m);
            }
        }
    }
    
    public void deactiveMapping(){
        lstActiveMapping.remove(Integer.valueOf(rowNo));
        Mapping_Parent_Obj__c m1 = new Mapping_Parent_Obj__c(Id=mapId,Is_Active__c=false,Is_Default_Mapping__c=false);
        update m1;
        for(Mapping_Parent_Obj__c m :lstMapParent){
            if(m.id == mapId){
                lstDeActiveMapping.add(m);
            }
        }
    }
    
    public void activeMapping(){
        lstDeActiveMapping.remove(Integer.valueOf(rowNo));
        Mapping_Parent_Obj__c m1 = new Mapping_Parent_Obj__c(Id=mapId,Is_Active__c=true);
        update m1;
        for(Mapping_Parent_Obj__c m :lstMapParent){
            if(m.id == mapId){
                lstActiveMapping.add(m);
            }
        }
    }
    
    public void deleteMapping(){
        for(Mapping_Parent_Obj__c m :lstMapParent){
            if(m.id == mapId){
                lstDeActiveMapping.remove(Integer.valueOf(rowNo));
            }
        }
        List<Mapping_Child_Obj__c> lstMpChld = [select id from Mapping_Child_Obj__c where Mapping_Parent_Obj__c =: mapId];
        if (Schema.sObjectType.Mapping_Child_Obj__c.isDeletable()){
            delete lstMpChld;
        }
        Mapping_Parent_Obj__c m1 = new Mapping_Parent_Obj__c(Id=mapId);
        if (Schema.sObjectType.Mapping_Parent_Obj__c.isDeletable()){
            delete m1;
        }
    }
    
    public PageReference goToCreateMapping(){
        PageReference pagRef = Page.mapping;
        pagRef.setRedirect(true);
        return pagRef;
    }
}