objects/Mapping_Parent_Obj__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Default_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default Mapping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Name__c</fullName>
        <label>Mapping Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>folder_name__c</fullName>
        <label>folder name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mapping Parent Obj</label>
    <nameField>
        <label>Mapping Parent Obj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Parent Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mapping_Profile_Access__c.object
<CustomObject>
    <fields>
        <fullName>Mapping_Parent_Obj__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mapping Parent Obj</label>
        <referenceTo>Mapping_Parent_Obj__c</referenceTo>
        <relationshipLabel>Mapping Profile Access</relationshipLabel>
        <relationshipName>Mapping_Profile_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Profile Access</label>
    <nameField>
        <label>Mapping Profile Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Profile Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MappingProfileAccessControllerTest.cls
@istest
public class MappingProfileAccessControllerTest {
    public static testmethod void MappingProfileAccessController(){
        MappingProfileAccessController mpactrl = new MappingProfileAccessController();
        mpactrl.getProfiles();
        mpactrl.saveData();
        List<Mapping_Parent_Obj__c> lstPrnt = [select id,Is_Default_Mapping__c from Mapping_Parent_Obj__c where Is_Default_Mapping__c = true];
        system.assertEquals(lstPrnt.get(0).Is_Default_Mapping__c, true);
    }
    
    @testSetup
    Static void insertTestData(){
        List<Profile> lpf= [SELECT Id,Name,UserType FROM Profile limit 10];
        String tempPrflId = '';
        for(Profile pobj : lpf){
            tempPrflId += pobj.Id + ',';
        }
        tempPrflId = tempPrflId.substring(0,tempPrflId.length() - 1);
        
        List<Mapping_Parent_Obj__c> lstPrnt = new List<Mapping_Parent_Obj__c>();
        Mapping_Parent_Obj__c mapOb1 = new Mapping_Parent_Obj__c();
        mapOb1.Mapping_Name__c = 'test mapping name';
        mapOb1.Is_Default_Mapping__c = true;
        mapOb1.Is_Active__c = true;
        mapOb1.folder_name__c = 'test folder name';
        lstPrnt.add(mapOb1);
        
        Mapping_Parent_Obj__c mapOb2 = new Mapping_Parent_Obj__c();
        mapOb2.Mapping_Name__c = 'test mapping name';
        mapOb2.Is_Default_Mapping__c = true;
        mapOb2.Is_Active__c = true;
        mapOb2.folder_name__c = 'test folder name';
        lstPrnt.add(mapOb2);
        
        Mapping_Parent_Obj__c mapOb3 = new Mapping_Parent_Obj__c();
        mapOb3.Mapping_Name__c = 'test mapping name';
        mapOb3.Is_Default_Mapping__c = true;
        mapOb3.Is_Active__c = true;
        mapOb3.folder_name__c = 'test folder name';
        lstPrnt.add(mapOb3);
        insert lstPrnt;
        
        List<Mapping_Profile_Access__c> lstPrfl = new List<Mapping_Profile_Access__c>();
        Mapping_Profile_Access__c mpaObj = new Mapping_Profile_Access__c();
        mpaObj.Mapping_Parent_Obj__c = mapOb1.Id;
        mpaObj.Profile_Id__c = tempPrflId;
        lstPrfl.add(mpaObj);
        
        Mapping_Profile_Access__c mpaObj1 = new Mapping_Profile_Access__c();
        mpaObj1.Mapping_Parent_Obj__c = mapOb2.Id;
        mpaObj1.Profile_Id__c = lpf.get(0).Id;
        lstPrfl.add(mpaObj1);
        
        Mapping_Profile_Access__c mpaObj2 = new Mapping_Profile_Access__c();
        mpaObj2.Mapping_Parent_Obj__c = mapOb3.Id;
        lstPrfl.add(mpaObj2);
        insert lstPrfl;
        
        system.assertEquals(mapOb3.Is_Active__c, true);
    }
}